import {
  formationPreset,
  player,
  step,
} from "@/lib/tactics-presets/helpers";
import type { TacticsPreset } from "@/lib/tactics-presets/types";

export const FORMATION_PRESETS_11V11: TacticsPreset[] = [
  formationPreset({
    id: "formation-11v11-4-3-3",
    title: "11v11 4-3-3",
    shortDescription:
      "A balanced, expansive shape with a back four, midfield three, and front three.",
    format: "11v11",
    playerCount: 11,
    goalkeeperCount: 1,
    ageGuidance: "U13 and older",
    difficulty: "developing",
    objectives: [
      "Create width in possession while maintaining strong central connections.",
      "Press and defend with coordinated units of three.",
    ],
    setupInstructions: [
      "Place the goalkeeper behind a back four.",
      "Set one holding midfielder behind two central midfielders.",
      "Position two wingers outside a central striker.",
    ],
    coachingPoints: [
      "The holding midfielder offers a passing angle and protects the center.",
      "Wingers hold width until space opens for an inside run.",
      "Fullbacks coordinate forward movement with the winger on their side.",
    ],
    tags: ["11v11", "formation", "balanced", "front-three", "width"],
    steps: [
      step(
        "formation-11v11-4-3-3-step-1",
        0,
        "Step 1",
        [
          player("formation-11v11-4-3-3-gk", "home", 0.07, 0.5, "GK"),
          player("formation-11v11-4-3-3-lb", "home", 0.25, 0.12, "LB"),
          player("formation-11v11-4-3-3-lcb", "home", 0.22, 0.37, "LCB"),
          player("formation-11v11-4-3-3-rcb", "home", 0.22, 0.63, "RCB"),
          player("formation-11v11-4-3-3-rb", "home", 0.25, 0.88, "RB"),
          player("formation-11v11-4-3-3-dm", "home", 0.42, 0.5, "DM"),
          player("formation-11v11-4-3-3-lcm", "home", 0.52, 0.32, "LCM"),
          player("formation-11v11-4-3-3-rcm", "home", 0.52, 0.68, "RCM"),
          player("formation-11v11-4-3-3-lw", "home", 0.75, 0.14, "LW"),
          player("formation-11v11-4-3-3-st", "home", 0.79, 0.5, "ST"),
          player("formation-11v11-4-3-3-rw", "home", 0.75, 0.86, "RW"),
        ],
        "Starting positions for the 4-3-3 formation.",
      ),
    ],
  }),
  formationPreset({
    id: "formation-11v11-4-2-3-1",
    title: "11v11 4-2-3-1",
    shortDescription:
      "A flexible shape using a double pivot behind three attacking midfielders and one striker.",
    format: "11v11",
    playerCount: 11,
    goalkeeperCount: 1,
    ageGuidance: "U13 and older",
    difficulty: "developing",
    objectives: [
      "Control central spaces with a double pivot.",
      "Create combinations between the attacking midfield line and striker.",
    ],
    setupInstructions: [
      "Place the goalkeeper behind a back four.",
      "Position two holding midfielders in front of the center backs.",
      "Set a central attacking midfielder between two wide attackers behind one striker.",
    ],
    coachingPoints: [
      "The two holding midfielders stagger so one can advance while one protects.",
      "The attacking midfielder finds space between the opposition's lines.",
      "Wide attackers recover alongside the midfield when defending.",
    ],
    tags: ["11v11", "formation", "double-pivot", "number-ten", "single-striker"],
    steps: [
      step(
        "formation-11v11-4-2-3-1-step-1",
        0,
        "Step 1",
        [
          player("formation-11v11-4-2-3-1-gk", "home", 0.07, 0.5, "GK"),
          player("formation-11v11-4-2-3-1-lb", "home", 0.24, 0.12, "LB"),
          player("formation-11v11-4-2-3-1-lcb", "home", 0.21, 0.37, "LCB"),
          player("formation-11v11-4-2-3-1-rcb", "home", 0.21, 0.63, "RCB"),
          player("formation-11v11-4-2-3-1-rb", "home", 0.24, 0.88, "RB"),
          player("formation-11v11-4-2-3-1-ldm", "home", 0.42, 0.38, "LDM"),
          player("formation-11v11-4-2-3-1-rdm", "home", 0.42, 0.62, "RDM"),
          player("formation-11v11-4-2-3-1-lam", "home", 0.6, 0.18, "LAM"),
          player("formation-11v11-4-2-3-1-cam", "home", 0.58, 0.5, "CAM"),
          player("formation-11v11-4-2-3-1-ram", "home", 0.6, 0.82, "RAM"),
          player("formation-11v11-4-2-3-1-st", "home", 0.79, 0.5, "ST"),
        ],
        "Starting positions for the 4-2-3-1 formation.",
      ),
    ],
  }),
  formationPreset({
    id: "formation-11v11-4-4-2",
    title: "11v11 4-4-2",
    shortDescription:
      "A clear, compact shape with two banks of four supporting a forward pair.",
    format: "11v11",
    playerCount: 11,
    goalkeeperCount: 1,
    ageGuidance: "U13 and older",
    objectives: [
      "Defend compactly with two connected lines of four.",
      "Attack with width and complementary movement from two forwards.",
    ],
    setupInstructions: [
      "Place the goalkeeper behind a back four.",
      "Arrange four midfielders across the pitch in front of the defenders.",
      "Position two forwards centrally and stagger their starting heights.",
    ],
    coachingPoints: [
      "Keep short vertical and horizontal distances between the two lines of four.",
      "Wide midfielders support their fullbacks before breaking forward.",
      "One forward checks toward the ball while the other threatens space behind.",
    ],
    tags: ["11v11", "formation", "compact", "two-banks", "two-forwards"],
    steps: [
      step(
        "formation-11v11-4-4-2-step-1",
        0,
        "Step 1",
        [
          player("formation-11v11-4-4-2-gk", "home", 0.07, 0.5, "GK"),
          player("formation-11v11-4-4-2-lb", "home", 0.24, 0.12, "LB"),
          player("formation-11v11-4-4-2-lcb", "home", 0.21, 0.37, "LCB"),
          player("formation-11v11-4-4-2-rcb", "home", 0.21, 0.63, "RCB"),
          player("formation-11v11-4-4-2-rb", "home", 0.24, 0.88, "RB"),
          player("formation-11v11-4-4-2-lm", "home", 0.49, 0.14, "LM"),
          player("formation-11v11-4-4-2-lcm", "home", 0.46, 0.38, "LCM"),
          player("formation-11v11-4-4-2-rcm", "home", 0.46, 0.62, "RCM"),
          player("formation-11v11-4-4-2-rm", "home", 0.49, 0.86, "RM"),
          player("formation-11v11-4-4-2-lf", "home", 0.74, 0.38, "LF"),
          player("formation-11v11-4-4-2-rf", "home", 0.77, 0.62, "RF"),
        ],
        "Starting positions for the 4-4-2 formation.",
      ),
    ],
  }),
  formationPreset({
    id: "formation-11v11-3-5-2",
    title: "11v11 3-5-2",
    shortDescription:
      "A central-overload shape with three center backs, wingbacks, three midfielders, and two forwards.",
    format: "11v11",
    playerCount: 11,
    goalkeeperCount: 1,
    ageGuidance: "U14 and older",
    difficulty: "advanced",
    objectives: [
      "Overload central midfield while preserving width through wingbacks.",
      "Build securely with a three-player defensive line.",
    ],
    setupInstructions: [
      "Place the goalkeeper behind three center backs.",
      "Set two wingbacks outside a midfield triangle.",
      "Position two forwards centrally and at complementary heights.",
    ],
    coachingPoints: [
      "Wingbacks provide width in possession and recover into the back line without it.",
      "The holding midfielder stays connected to the center backs.",
      "The outside center backs can advance only when the remaining players secure defensive balance.",
    ],
    tags: ["11v11", "formation", "back-three", "wingbacks", "central-overload"],
    steps: [
      step(
        "formation-11v11-3-5-2-step-1",
        0,
        "Step 1",
        [
          player("formation-11v11-3-5-2-gk", "home", 0.07, 0.5, "GK"),
          player("formation-11v11-3-5-2-lcb", "home", 0.24, 0.25, "LCB"),
          player("formation-11v11-3-5-2-cb", "home", 0.21, 0.5, "CB"),
          player("formation-11v11-3-5-2-rcb", "home", 0.24, 0.75, "RCB"),
          player("formation-11v11-3-5-2-lwb", "home", 0.48, 0.1, "LWB"),
          player("formation-11v11-3-5-2-dm", "home", 0.42, 0.5, "DM"),
          player("formation-11v11-3-5-2-lcm", "home", 0.54, 0.34, "LCM"),
          player("formation-11v11-3-5-2-rcm", "home", 0.54, 0.66, "RCM"),
          player("formation-11v11-3-5-2-rwb", "home", 0.48, 0.9, "RWB"),
          player("formation-11v11-3-5-2-lf", "home", 0.76, 0.39, "LF"),
          player("formation-11v11-3-5-2-rf", "home", 0.78, 0.61, "RF"),
        ],
        "Starting positions for the 3-5-2 formation.",
      ),
    ],
  }),
  formationPreset({
    id: "formation-11v11-3-4-3",
    title: "11v11 3-4-3",
    shortDescription:
      "An aggressive shape with three center backs, a four-player midfield, and a wide front three.",
    format: "11v11",
    playerCount: 11,
    goalkeeperCount: 1,
    ageGuidance: "U14 and older",
    difficulty: "advanced",
    objectives: [
      "Occupy all five attacking lanes with wingbacks and a front three.",
      "Apply immediate pressure with numbers around the ball.",
    ],
    setupInstructions: [
      "Place the goalkeeper behind three center backs.",
      "Arrange two central midfielders between two wingbacks.",
      "Set two wingers outside a central striker.",
    ],
    coachingPoints: [
      "Wingbacks recover quickly to prevent opponents attacking outside the back three.",
      "Central midfielders balance support beneath the front line with transition protection.",
      "The front three coordinate pressure to force play toward one touchline.",
    ],
    tags: ["11v11", "formation", "back-three", "front-three", "high-press"],
    steps: [
      step(
        "formation-11v11-3-4-3-step-1",
        0,
        "Step 1",
        [
          player("formation-11v11-3-4-3-gk", "home", 0.07, 0.5, "GK"),
          player("formation-11v11-3-4-3-lcb", "home", 0.24, 0.25, "LCB"),
          player("formation-11v11-3-4-3-cb", "home", 0.21, 0.5, "CB"),
          player("formation-11v11-3-4-3-rcb", "home", 0.24, 0.75, "RCB"),
          player("formation-11v11-3-4-3-lwb", "home", 0.49, 0.11, "LWB"),
          player("formation-11v11-3-4-3-lcm", "home", 0.46, 0.39, "LCM"),
          player("formation-11v11-3-4-3-rcm", "home", 0.46, 0.61, "RCM"),
          player("formation-11v11-3-4-3-rwb", "home", 0.49, 0.89, "RWB"),
          player("formation-11v11-3-4-3-lw", "home", 0.74, 0.15, "LW"),
          player("formation-11v11-3-4-3-st", "home", 0.79, 0.5, "ST"),
          player("formation-11v11-3-4-3-rw", "home", 0.74, 0.85, "RW"),
        ],
        "Starting positions for the 3-4-3 formation.",
      ),
    ],
  }),
];
